---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: yucca-metrics-object-user
  namespace: flux-system
spec:
  targetNamespace: yucca
  commonMetadata:
    labels:
      app.kubernetes.io/name: yucca-metrics-object-user
  path: ./kubernetes/apps/yucca/metrics-object-user/app
  prune: true
  wait: true
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: yucca
  dependsOn:
    - name: rook-ceph-cluster
