#!/usr/bin/env bash
#MISE description="Build yucca-sdk/orchestration-ui"
#MISE depends=["yucca-sdk:orchestration-ui:generate-fetch-client"]
set -e

NODE_ENV=production pnpm --filter orchestration-ui build
