#!/usr/bin/env bash
#MISE description="yucca-api: sync OpenAPI specification"
#MISE dir="{{config_root}}/packages/yucca-api"
#MISE depends=["yucca-api:build"]
set -e

NODE_ENV=development node dist/bin/sync-openapi.js
