packages:
  - packages/*
  - packages/yucca-sdk/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - better-sqlite3
  - esbuild
  - protobufjs
  - unrs-resolver

catalog:
  '@aws-sdk/client-s3': ^3.965.0
  '@aws-sdk/lib-storage': ^3.965.0
  '@eslint/js': ^9.39.2
  '@futo-org/restic-wrapper': 1.3.0
  '@immich/sql-tools': ^0.3.2
  '@immich/ui': ^0.59.0
  '@jest/globals': ^30.2.0
  '@lingui/cli': ^5.8.0
  '@lingui/core': ^5.8.0
  '@mdi/js': ^7.4.47
  '@nestjs/cli': ^11.0.14
  '@nestjs/common': ^11.1.13
  '@nestjs/core': ^11.1.11
  '@nestjs/event-emitter': ^3.0.1
  '@nestjs/jwt': ^11.0.2
  '@nestjs/platform-express': ^11.0.1
  '@nestjs/platform-socket.io': ^11.1.14
  '@nestjs/schedule': ^6.1.1
  '@nestjs/schematics': ^11.0.9
  '@nestjs/swagger': ^11.2.5
  '@nestjs/testing': ^11.1.11
  '@nestjs/websockets': ^11.1.14
  '@oazapfts/runtime': ^1.1.0
  '@opentelemetry/api': ^1.9.0
  '@opentelemetry/context-async-hooks': ^2.5.0
  '@opentelemetry/core': ^2.5.0
  '@opentelemetry/exporter-logs-otlp-proto': ^0.211.0
  '@opentelemetry/exporter-metrics-otlp-proto': ^0.211.0
  '@opentelemetry/exporter-trace-otlp-proto': ^0.211.0
  '@opentelemetry/instrumentation-pino': ^0.57.0
  '@opentelemetry/propagator-b3': ^2.5.0
  '@opentelemetry/propagator-jaeger': ^2.5.0
  '@opentelemetry/sdk-node': ^0.217.0
  '@playwright/test': 1.59.1
  '@sveltejs/adapter-auto': ^7.0.0
  '@sveltejs/adapter-node': ^5.5.4
  '@sveltejs/kit': ^2.50.1
  '@sveltejs/package': ^2.5.7
  '@sveltejs/vite-plugin-svelte': ^6.2.4
  '@tailwindcss/vite': ^4.1.18
  '@tanstack/svelte-query': ^6.1.3
  '@types/better-sqlite3': ^7.6.13
  '@types/d3': ^7.4.3
  '@types/express': ^5.0.6
  '@types/jest': ^30.0.0
  '@types/jsonwebtoken': ^9.0.10
  '@types/lodash.debounce': ^4.0.9
  '@types/luxon': ^3.7.1
  '@types/ms': ^2.1.0
  '@types/node': ^25.2.1
  '@types/oidc-provider': ^9.5.0
  '@types/supertest': ^6.0.2
  '@types/tail': ^2.2.3
  '@vitest/browser': ^4.0.18
  '@vitest/browser-playwright': ^4.0.18
  aws4fetch: ^1.0.20
  better-sqlite3: ^12.6.2
  class-transformer: ^0.5.1
  class-validator: ^0.14.3
  cookie: ^1.1.1
  cron: ^4.4.0
  cron-validate: ^1.5.3
  cronstrue: ^3.14.0
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-unicorn: ^62.0.0
  event-iterator: ^2.0.0
  eventsource-client: ^1.2.0
  express: ^5.2.1
  globals: ^16.0.0
  jest: ^30.2.0
  jest-extended: ^7.0.0
  jsonwebtoken: ^9.0.3
  kysely: 0.28.2
  kysely-postgres-js: ^3.0.0
  lodash.debounce: ^4.0.8
  luxon: ^3.7.2
  nestjs-kysely: ^3.1.2
  nestjs-otel: ^8.0.2
  nodemon: ^3.1.11
  oazapfts: ^7.0.1
  oidc-provider: ^9.8.3
  openid-client: ^6.8.1
  pino: ^10.3.0
  pino-pretty: ^13.1.3
  playwright: 1.59.1
  postgres: ^3.4.8
  prettier: ^3.7.4
  prettier-plugin-organize-imports: ^4.3.0
  prettier-plugin-svelte: ^3.4.1
  prettier-plugin-tailwindcss: ^0.7.2
  publint: ^0.3.17
  reflect-metadata: ^0.2.2
  rxjs: ^7.8.2
  socket.io: ^4.8.3
  socket.io-client: ^4.8.3
  source-map-support: ^0.5.21
  supertest: ^7.0.0
  svelte: ^5.48.2
  svelte-check: ^4.3.5
  svelte-i18n-lingui: ^0.2.2
  tail: ^2.2.6
  tailwindcss: ^4.1.18
  ts-jest: ^29.4.6
  ts-loader: ^9.5.4
  ts-node: ^10.9.2
  tsconfig-paths: ^4.2.0
  tsx: ^4.20.6
  typescript: ^5.9.3
  typescript-eslint: ^8.52.0
  vite: ^7.3.1
  vitest: ^4.0.18
  vitest-browser-svelte: ^2.0.2
  zod: ^4.3.5
