apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: {{ .Values.userName }}
spec:
  store: {{ .Values.store }}
  clusterNamespace: {{ .Values.clusterNamespace }}
  displayName: {{ .Values.userName }}
  {{- with .Values.capabilities }}
  capabilities:
    {{- toYaml . | nindent 4 }}
  {{- end }}
