---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: yucca-metrics-worker
  namespace: yucca
spec:
  interval: 1h
  chart:
    spec:
      chart: charts/yucca-metrics-worker
      sourceRef:
        kind: GitRepository
        name: yucca
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/immich-app/yucca/yucca-metrics-worker # TODO: confirm prod registry
      tag: 0.0.1
