[tools]
node = "25.4.0"
pnpm = "10.28.1"
restic = "0.18.0"

gh = "2.25.0"
"github:git-town/git-town" = "22.4.0"

[tasks.dev]
description = "Start all services in development mode"
depends = ["install:deps", "common:build", "docker:start"]
run = [{ task = "*:dev" }]

[tasks.build]
description = "Build all packages"
depends = ["*:build"]

[tasks."common:build"]
description = "Build all common packages"
depends = ["common:*:build"]

[tasks.test]
description = "Run all unit tests"
depends = ["*:test"]

[tasks."test:integration"]
description = "Run all integration tests"
run = [{ task = "*:test:integration" }]

[tasks."test:e2e:web"]
description = "Run all web e2e tests"
run = [{ task = "test:e2e:wait" }, { task = "*:test:e2e:web" }]

[tasks."prepare"]
description = "Install and build packages"
run = [{ task = "install:frozen" }, { task = "build" }]

[tasks."check"]
description = "Run checks & unit tests"
run = [{ tasks = ["lint", "*:check"] }, { task = "format" }, { task = "test" }]

[tasks.fix]
description = "Run all possible code fixes"
run = [{ task = "*:fix" }, { task = "web:lingui" }]
