[tools]
node = "25.4.0"
pnpm = "10.28.1"
go = "1.24"
restic = "0.18.0"

gh = "2.25.0"
"github:git-town/git-town" = "22.4.0"

[tasks.dev]
description = "Start all services in development mode"
depends = ["install:deps", "common:build", "docker:start"]
run = [{ task = "*:dev" }]

[tasks.build]
description = "Build all packages"
depends = ["*:build"]

[tasks."common:build"]
description = "Build all common packages"
depends = ["install:deps", "common:*:build"]

[tasks.test]
description = "Run all unit tests"
depends = ["*:test"]

[tasks."test:integration"]
description = "Run all integration tests"
run = [{ task = "*:test:integration" }]

[tasks."test:e2e:web"]
description = "Run all web e2e tests"
run = [{ task = "test:e2e:wait" }, { task = "*:test:e2e:web" }]

[tasks."prepare"]
description = "Install and build packages"
run = [{ task = "install:frozen" }, { task = "build" }]

[tasks."check"]
description = "Run checks & unit tests"
run = [{ tasks = ["lint", "*:check"] }, { task = "format" }, { task = "test" }]

[tasks.fix]
description = "Run all possible code fixes"
run = [{ task = "*:fix" }, { task = "web:lingui" }]

[env]
# default environment variables for development
NODE_ENV = "development"
YUCCA_API_PORT = 3020
RESTIC_API_PORT = 3010
S3_ACCESS_KEY_ID = "minio"
S3_SECRET_ACCESS_KEY = "miniominio"
S3_REGION = "minio"
S3_ENDPOINT = "http://localhost:9000"
S3_FORCE_PATH_STYLE = true
POSTGRES_HOST = "localhost"
POSTGRES_USERNAME = "postgres"
POSTGRES_PASSWORD = "postgres"
POSTGRES_DATABASE = "yucca"
POSTGRES_PORT = 15432
JWT_SECRET = "cca13c34b450a77c1d4b9ecd25dff6aebc6d7417afdb31864f5943c59abd03a1"
OIDC_ISSUER = "http://localhost:8092"
OIDC_CLIENT_ID = "client ID"
OIDC_CLIENT_SECRET = "client secret"
OIDC_ALLOW_INSECURE = true
OIDC_REDIRECT_URI = 'http://localhost:5173/api/auth/oidc/callback'
OIDC_LOGOUT_REDIRECT_URI = 'http://localhost:5173'
LOG_LEVEL = "debug"
OTLP_METRICS_ENDPOINT = "localhost:8428"
OTLP_METRICS_URL_PATH = "/opentelemetry/v1/metrics"
OTLP_LOGS_ENDPOINT = "localhost:9428"
OTLP_LOGS_URL_PATH = "/insert/opentelemetry/v1/logs"
